src/WTTechPortal/Models/Inventory/assetinventory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using WTTechPortal.Models.Assests;

using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WTTechPortal.Models.Inventory
{
    public class assetinventory
    {
        [Key]
        public int id { get; set; }
        [Display(Name = "Asset Type")]
        public int assettype { get; set; }
        [Display(Name = "Asset Orginzation")]
        public int org { get; set; }
        [Display(Name = "Asset ID")]
        public string assetid { get; set; }
        [Display(Name = "HDD Size")]
        public int hddsize { get; set; }
        [Display(Name = "Memory Installed")]
        public int memory { get; set; }
        [Display(Name = "Asset Status")]
        public int ready { get; set; }
        [Display(Name = "Notes")]
        public string notes { get; set; }
        [Display(Name = "Operating System")]
        public int operatingsystem { get; set; }
        [Display(Name = "Model")]
        public string model { get; set; }
        [Display(Name = "Brand")]
        public int brand { get; set; }
        [Display(Name = "CPU Speed")]
        public decimal cpuspd { get; set; }
        [Display(Name = "CPU Cores")]
        public int cpucores { get; set; }
        [Display(Name = "CPU Model")]
        public string cpumodel { get; set; }

        [ForeignKey("brand")]
        public asset_model brands { get; set; }

        [ForeignKey("org")]
        public org_list orginzation { get; set; }

        [ForeignKey("ready")]
        public asset_status status { get; set; }

        [ForeignKey("assettype")]
        public asset_type assettypes { get; set; }

        [ForeignKey("operatingsystem")]
        public asset_opertaingsystem operatingsystems { get; set; }


    }
}

src/WTTechPortal/Controllers/AssetInventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WTTechPortal.Data;
using WTTechPortal.Models.Inventory;
using WTTechPortal.Models;
using Microsoft.AspNetCore.Authorization;

namespace WTTechPortal.Controllers
{
    [Authorize]
    public class AssetInventoryController : Controller
    {
        private readonly WttechportalDbContext _context;

        public AssetInventoryController(WttechportalDbContext context)
        {
            _context = context;    
        }

        // GET: AssetInventory
        public async Task<IActionResult> Index(int? assetstatus, int? brand, int? opertaingsystem)
        {
            var wttechportalDbContext = (from a in _context.assetinventory select a);

            var modelist = _context.asset_model.OrderBy(c => c.id).Select(x => new { Id = x.id, Value = x.model });
            var statuslist = _context.asset_status.OrderBy(c => c.id).Select(x => new { Id = x.id, Value = x.assetstatus });
            var operatingsystemlist = _context.asset_opertaingsystem.OrderBy(c => c.id).Select(x => new { Id = x.id, Value = x.operatingsystem });
            ViewBag.modelist = new SelectList(modelist, "Id", "Value");
            ViewBag.statuslist = new SelectList(statuslist, "Id", "Value");
            ViewBag.operatingsystemlist = new SelectList(operatingsystemlist, "Id", "Value");

            // Resutls Count
            ViewBag.totalassets = wttechportalDbContext.Count();
            ViewBag.assetsready = wttechportalDbContext.Where(x => x.ready.Equals(1)).Count();
            ViewBag.assetsreadyneedrepair = wttechportalDbContext.Where(x => x.ready.Equals(6)).Count();
            ViewBag.assestsneedrepair = wttechportalDbContext.Where(x => x.ready.Equals(2)).Count();
            ViewBag.assetsunchecked = wttechportalDbContext.Where(x => x.ready.Equals(5)).Count();
            ViewBag.functionalneedos = wttechportalDbContext.Where(x => x.ready.Equals(3)).Count();
            ViewBag.assetsnotusable = wttechportalDbContext.Where(x => x.ready.Equals(4)).Count();

            // var wttechportalDbContext = _context.assetinventory.Include(a => a.assettypes).Include(a => a.brands).Include(a => a.operatingsystems).Include(a => a.orginzation).Include(a => a.status).OrderBy(a => a.ready);


            if (assetstatus != null)
            {
                wttechportalDbContext = wttechportalDbContext.Where(a => a.ready.Equals(assetstatus));
            }

            if (brand != null)
            {
                wttechportalDbContext = wttechportalDbContext.Where(a => a.brand.Equals(brand));

            }
            if (opertaingsystem != null)
            {
                wttechportalDbContext = wttechportalDbContext.Where(a => a.operatingsystem.Equals(opertaingsystem));
            }

            wttechportalDbContext = wttechportalDbContext.Include(a => a.assettypes).Include(a => a.brands).Include(a => a.operatingsystems).Include(a => a.orginzation).Include(a => a.status).OrderBy(a => a.ready);

            ViewBag.results = wttechportalDbContext.Count();

            return View(await wttechportalDbContext.ToListAsync());
        }


        // GET: AssetInventory/Create
        public IActionResult Create()
        {

            ViewData["assettype"] = new SelectList(_context.asset_type, "id", "assettype");
            ViewData["brand"] = new SelectList(_context.asset_model, "id", "model");
            ViewData["operatingsystem"] = new SelectList(_context.asset_opertaingsystem, "id", "operatingsystem");
            ViewData["org"] = new SelectList(_context.org_list, "id", "orgname");
            ViewData["ready"] = new SelectList(_context.asset_status, "id", "assetstatus");
            return View();
        }

        // POST: AssetInventory/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,assetid,assettype,brand,cpucores,cpumodel,cpuspd,hddsize,memory,model,notes,operatingsystem,org,ready")] assetinventory assetinventory)
        {
            if (ModelState.IsValid)
            {
                _context.Add(assetinventory);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["assettype"] = new SelectList(_context.asset_type, "id", "assettype", assetinventory.assettype);
            ViewData["brand"] = new SelectList(_context.asset_model, "id", "model", assetinventory.brand);
            ViewData["operatingsystem"] = new SelectList(_context.asset_opertaingsystem, "id", "operatingsystem", assetinventory.operatingsystem);
            ViewData["org"] = new SelectList(_context.org_list, "id", "orgname", assetinventory.org);
            ViewData["ready"] = new SelectList(_context.asset_status, "id", "assetstatus", assetinventory.ready);
            return View(assetinventory);
        }

        // GET: AssetInventory/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assetinventory = await _context.assetinventory.SingleOrDefaultAsync(m => m.id == id);
            if (assetinventory == null)
            {
                return NotFound();
            }
            ViewData["assettype"] = new SelectList(_context.asset_type, "id", "assettype", assetinventory.assettype);
            ViewData["brand"] = new SelectList(_context.asset_model, "id", "model", assetinventory.brand);
            ViewData["operatingsystem"] = new SelectList(_context.asset_opertaingsystem, "id", "operatingsystem", assetinventory.operatingsystem);
            ViewData["org"] = new SelectList(_context.org_list, "id", "orgname", assetinventory.org);
            ViewData["ready"] = new SelectList(_context.asset_status, "id", "assetstatus", assetinventory.ready);
            return View(assetinventory);
        }

        // POST: AssetInventory/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,assetid,assettype,brand,cpucores,cpumodel,cpuspd,hddsize,memory,model,notes,operatingsystem,org,ready")] assetinventory assetinventory)
        {
            if (id != assetinventory.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(assetinventory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!assetinventoryExists(assetinventory.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["assettype"] = new SelectList(_context.asset_type, "id", "assettype", assetinventory.assettype);
            ViewData["brand"] = new SelectList(_context.asset_model, "id", "model", assetinventory.brand);
            ViewData["operatingsystem"] = new SelectList(_context.asset_opertaingsystem, "id", "operatingsystem", assetinventory.operatingsystem);
            ViewData["org"] = new SelectList(_context.org_list, "id", "orgname", assetinventory.org);
            ViewData["ready"] = new SelectList(_context.asset_status, "id", "assetstatus", assetinventory.ready);
            return View(assetinventory);
        }

        // GET: AssetInventory/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var assetinventory = await _context.assetinventory.SingleOrDefaultAsync(m => m.id == id);
            if (assetinventory == null)
            {
                return NotFound();
            }

            return View(assetinventory);
        }

        // POST: AssetInventory/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var assetinventory = await _context.assetinventory.SingleOrDefaultAsync(m => m.id == id);
            _context.assetinventory.Remove(assetinventory);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool assetinventoryExists(int id)
        {
            return _context.assetinventory.Any(e => e.id == id);
        }
    }
}

src/WTTechPortal/Views/AssetInventory/Create.cshtml
@model WTTechPortal.Models.Inventory.assetinventory

@{
    ViewData["Title"] = "Create Asset";
}

<h2>@ViewBag.Title</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>assetinventory</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="assetid" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="assetid" class="form-control" />
                <span asp-validation-for="assetid" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="assettype" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="assettype" class ="form-control" asp-items="ViewBag.assettype"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="brand" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="brand" class ="form-control" asp-items="ViewBag.brand"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="cpucores" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="cpucores" class="form-control" />
                <span asp-validation-for="cpucores" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="cpumodel" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="cpumodel" class="form-control" />
                <span asp-validation-for="cpumodel" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="cpuspd" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="cpuspd" class="form-control" />
                <span asp-validation-for="cpuspd" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="hddsize" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="hddsize" class="form-control" />
                <span asp-validation-for="hddsize" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="memory" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="memory" class="form-control" />
                <span asp-validation-for="memory" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="model" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="model" class="form-control" />
                <span asp-validation-for="model" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="notes" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="notes" class="form-control" />
                <span asp-validation-for="notes" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="operatingsystem" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="operatingsystem" class ="form-control" asp-items="ViewBag.operatingsystem"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="org" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="org" class ="form-control" asp-items="ViewBag.org"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ready" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="ready" class ="form-control" asp-items="ViewBag.ready"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/WTTechPortal/Views/AssetInventory/Delete.cshtml
@model WTTechPortal.Models.Inventory.assetinventory

@{
    ViewData["Title"] = "Delete Asset";
}

<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>assetinventory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.assetid)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.assetid)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.cpucores)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.cpucores)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.cpumodel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.cpumodel)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.cpuspd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.cpuspd)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.hddsize)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.hddsize)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.memory)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.memory)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.model)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.model)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.notes)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/WTTechPortal/Views/AssetInventory/Details.cshtml
@model WTTechPortal.Models.Inventory.assetinventory

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>assetinventory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.assetid)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.assetid)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.cpucores)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.cpucores)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.cpumodel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.cpumodel)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.cpuspd)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.cpuspd)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.hddsize)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.hddsize)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.memory)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.memory)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.model)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.model)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.notes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.notes)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/WTTechPortal/Views/AssetInventory/Edit.cshtml
@model WTTechPortal.Models.Inventory.assetinventory

@{
    ViewData["Title"] = "Edit Asset";
}

<h2>@ViewBag.Title</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>assetinventory</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="id" />
        <div class="form-group">
            <label asp-for="assetid" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="assetid" class="form-control" />
                <span asp-validation-for="assetid" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="assettype" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="assettype" class="form-control" asp-items="ViewBag.assettype"></select>
                <span asp-validation-for="assettype" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="brand" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="brand" class="form-control" asp-items="ViewBag.brand"></select>
                <span asp-validation-for="brand" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="cpucores" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="cpucores" class="form-control" />
                <span asp-validation-for="cpucores" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="cpumodel" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="cpumodel" class="form-control" />
                <span asp-validation-for="cpumodel" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="cpuspd" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="cpuspd" class="form-control" />
                <span asp-validation-for="cpuspd" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="hddsize" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="hddsize" class="form-control" />
                <span asp-validation-for="hddsize" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="memory" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="memory" class="form-control" />
                <span asp-validation-for="memory" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="model" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="model" class="form-control" />
                <span asp-validation-for="model" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="notes" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="notes" class="form-control" />
                <span asp-validation-for="notes" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="operatingsystem" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="operatingsystem" class="form-control" asp-items="ViewBag.operatingsystem"></select>
                <span asp-validation-for="operatingsystem" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="org" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="org" class="form-control" asp-items="ViewBag.org"></select>
                <span asp-validation-for="org" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ready" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="ready" class="form-control" asp-items="ViewBag.ready"></select>
                <span asp-validation-for="ready" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/WTTechPortal/Views/AssetInventory/Index.cshtml
@model IEnumerable<WTTechPortal.Models.Inventory.assetinventory>

@{
    ViewData["Title"] = "Asset Inventory";
}

<h2>@ViewBag.Title</h2>



@{
    SelectList modelist = ViewBag.modelist;
    SelectList statuslist = ViewBag.statuslist;
    SelectList operatingsystemlist = ViewBag.operatingsystemlist;
    string emailstatus = ViewBag.EmailStatus;
}

<p>
    <a asp-action="Create">Create New</a>
</p>

<p>
    @using (Html.BeginForm("Index", "AssetInventory", FormMethod.Post))
    {

        <text>Filter By Brand: </text> @Html.DropDownList("brand", modelist, "Show All")<br />
        <text>Filter By Status: </text> @Html.DropDownList("assetstatus", statuslist, "Show All")<br />
        <text>Filter By Operating System: </text> @Html.DropDownList("opertaingsystem", operatingsystemlist, "Show All") <br />
        

        <input type="submit" value="Search" />
    }





    @Html.ActionLink("Reset Filters", "Index")


</p>

<div id="results">
    Current Results :  @ViewBag.totalassets <br /> <br />
    Total Assets :  @ViewBag.totalassets <br />
    Total Assets Ready :  @ViewBag.assetsready <br />
    Total Assets Ready that have damage :  @ViewBag.assetsreadyneedrepair <br />
    Total Assets that Need Repaired :  @ViewBag.assestsneedrepair <br />
    Total Assets that need an Operating System :  @ViewBag.functionalneedos <br />
    Total Assets Unchecked :  @ViewBag.assetsunchecked <br />
    Total Assets that are not usable :  @ViewBag.assetsnotusable <br />
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.assetid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cpucores)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cpumodel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cpuspd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.hddsize)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.memory)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.operatingsystem)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ready)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.notes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.assetid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cpucores)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cpumodel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cpuspd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.hddsize)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.memory)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.operatingsystems.operatingsystem)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status.assetstatus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.notes)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |               
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>