src/WTTechPortal/Models/IPAM/ipam.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WTTechPortal.Models.IPAM
{
    public class ipam
    {
        [Key]
        public int id { get; set; }
        [Display(Name = "IP")]
        public string ip { get; set; }
        [Display(Name = "Ping")]
        public string ping { get; set; }
        [Display(Name = "DNS HostName")]
        public string hostname { get; set; }
        [Display(Name = "Ports")]
        public string ports { get; set; }
        public int org { get; set; }
        [Display(Name = "Date Last Scanned")]
        public DateTime date { get; set; }
        [Display(Name = "State")]
        public string state { get; set; }

        [ForeignKey("org")]
        public org_list orginzation { get; set; }

    }
}

src/WTTechPortal/Controllers/ipamController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WTTechPortal.Data;
using WTTechPortal.Models;
using Sakura.AspNetCore;
using WTTechPortal.Models.IPAM;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

namespace WTTechPortal.Controllers
{
    [Authorize]
    public class ipamController : Controller
    {
        private readonly WttechportalDbContext _context;

        public ipamController(WttechportalDbContext context)
        {
            _context = context;    
        }

        // GET: ipam
        public async Task<IActionResult> Index(string state, string searchstring)
        {
            var wttechportalDbContext = from i in _context.ipam select i;
            wttechportalDbContext = wttechportalDbContext.Include(i => i.orginzation);
            ViewBag.availableresults = wttechportalDbContext.Where(x => x.state.Equals("AVAILABLE")).Count();
            ViewBag.usedresults = wttechportalDbContext.Where(x => x.state.Equals("USED")).Count();
            var statelist = _context.ipam.OrderBy(c => c.state).Select(x => new { Id = x.state, Value = x.state }).Distinct();
            ViewBag.statelist = new SelectList(statelist, "Id", "Value");

            if (state != null)
            {
                wttechportalDbContext = wttechportalDbContext.Where(x => x.state.Equals(state)); 
            }
            if (searchstring != null)
            {
                wttechportalDbContext = from i in wttechportalDbContext
                                        where (i.ip.Contains(searchstring) || i.hostname.Contains(searchstring))
                                        select i;
                                        
            }
            ViewBag.totalresults = wttechportalDbContext.Count();

            



            int pagenumb = 1;
            int pagesize = 100;
            return View(await wttechportalDbContext.ToPagedListAsync(pagesize,pagenumb) );
            
        }



        private bool ipamExists(int id)
        {
            return _context.ipam.Any(e => e.id == id);
        }
    }
}

src/WTTechPortal/Views/ipam/Index.cshtml
@model Sakura.AspNetCore.IPagedList<WTTechPortal.Models.IPAM.ipam>
@*
@model IPagedList<WTTechPortal.Models.IPAM.ipam>
    *@
@{
    ViewData["Title"] = "IP Address Management";
}
@{
    SelectList statelist = ViewBag.statelist;

}
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Index", "ipam", FormMethod.Get))
{
    <text>Filter By IP or HostName: </text> @Html.TextBox("searchstring") <br/><br />
    <text>Filter By State: </text> @Html.DropDownList("state", statelist, "Show All")<br /><br />

    <input type="submit" value="Search" />
}

<div id="results">   
    Total Results :  @ViewBag.totalresults <br/>
    Total Available IPs :  @ViewBag.availableresults <br />
    Total Used IPs :  @ViewBag.usedresults <br />
</div>



@Html.ActionLink("Reset Filters", "Index")

<table class="table">
    <thead>
        <tr>
            <th>
                IP
            </th>
            <th>
                HostName
            </th>
            <th>
                Ping
            </th>
            <th>
                Ports
            </th>
            <th>
                State
            </th>
            <th>
                Date
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.ip
            </td>
            <td>
                @item.hostname
            </td>
            <td>
                @item.ping
            </td>
            <td>
                @item.ports
            </td>
            <td>
               @item.state
            </td>
            <td>
                @item.date
            </td>

        </tr>
}
    </tbody>
</table>
<pager source="Model" />